### ISSUE TITLE
Data partnership (potential)

### ISSUE THREAD

**Issue by alexmerryman** [RTCovid/business-impact#19]
Referring back to conversations between USDR and folks at Google/Yelp, also re: Jackson's concerns about (daily) scraping data from APIs — keep things on the up and up from an organizational (USDR/RTCovid) standpoint ("front page of WaPo").

Can merge this with other issue(s) here? Possibly #5 or #7?

**Comment by suprenant** [comment]
Thanks @alexmerryman. I merged this with #5, where we can continue to refine as needed. Closing this up.
